POST http://{{host}}/api/days
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "day": "2021-12-25"
}

###
GET http://{{host}}/api/days/49
Accept: application/json
Authorization: Bearer {{token}}

###
GET http://{{host}}/api/days
Accept: application/json
Authorization: Bearer {{token}}

###
