POST http://{{host}}/api/days
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "day": "2020-04-05"
}

###
GET http://{{host}}/api/days/44
Accept: application/json
Authorization: Bearer {{token}}

###
GET http://{{host}}/api/days
Accept: application/json
Authorization: Bearer {{token}}

###
