POST http://{{host}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "dayId": 1,
  "sectionId": 1,
  "summary": "Nullam quis risus eget urna mollis ornare vel eu leo.",
  "rank": 120000
}


### Stop a task

PATCH http://{{host}}/api/tasks/10
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "start": null,
  "time": 1200
}

### Start a task

PATCH http://{{host}}/api/tasks/10
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "start": "2021-03-26T12:39:36.336Z",
  "time": 1200
}

### Get active task id

GET http://{{host}}/api/tasks/active
Accept: application/json
Authorization: Bearer {{token}}

### Get all tasks

GET http://{{host}}/api/tasks
Accept: application/json
Authorization: Bearer {{token}}

###
